export const actionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SELECT_PRODUCT: "SELECT_PRODUCT",
    REMOVE_SELECT_PRODUCT: "REM0VE_SELECT_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_ITEM: "REMOVE_ITEM",
    TOTAL_PRODUCT: "TOTAL_PRODUCT",
    INCREASE_ITEM: "INCREASE_ITEM",
    DECREASE_ITEM: "DECREASE_ITEM",
    LOGIN: "LOGIN",
    PAYMENT: "PAYMENT",

}